/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface BackButtonPage {
    }
    interface RegularButtonPage {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBackButtonPageElement extends Components.BackButtonPage, HTMLStencilElement {
    }
    var HTMLBackButtonPageElement: {
        prototype: HTMLBackButtonPageElement;
        new (): HTMLBackButtonPageElement;
    };
    interface HTMLRegularButtonPageElement extends Components.RegularButtonPage, HTMLStencilElement {
    }
    var HTMLRegularButtonPageElement: {
        prototype: HTMLRegularButtonPageElement;
        new (): HTMLRegularButtonPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "back-button-page": HTMLBackButtonPageElement;
        "regular-button-page": HTMLRegularButtonPageElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface BackButtonPage {
    }
    interface RegularButtonPage {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "back-button-page": BackButtonPage;
        "regular-button-page": RegularButtonPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "back-button-page": LocalJSX.BackButtonPage & JSXBase.HTMLAttributes<HTMLBackButtonPageElement>;
            "regular-button-page": LocalJSX.RegularButtonPage & JSXBase.HTMLAttributes<HTMLRegularButtonPageElement>;
        }
    }
}
